version: '3.8'

services:
  bot:
    build: .
    container_name: telegram-bot
    restart: always
    env_file:
      - .env.docker
    depends_on:
      - db
      - redis
    networks:
      - botnet
    ports:
      - "8443:8443"

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - botnet

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - botnet

networks:
  botnet:
    driver: bridge